input_digitado = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(input_digitado)))
print('Só tem espaços? {}'.format(input_digitado.isspace()))
print('É um número? {}'.format(input_digitado.isnumeric()))
print('É alfabético? {}'.format(input_digitado.isalpha()))
print('É alfanumérico? {}'.format(input_digitado.isalnum()))
print('Está em maiúsculas? {}'.format(input_digitado.isupper()))
print('Está em minúsculas? {}'.format(input_digitado.islower()))
print('Está capitalizada? {}'.format(input_digitado.istitle()))
